version: "3"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: apartment_db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - "5451:5432"

volumes:
  db: